### PR TITLE
Change private members to protected for better inheritance support

### PR DESCRIPTION
**Pull request by RichyHBM**

### CODE REVIEW

**Comment by RichyHBM** [comment]
Well the main issue I had was for example when inheriting to add the different fill color it was quite hard to get access to certain parts, specifically things like adding new attributes and stuff. In the end I needed to overwrite a number of functions without calling the parent function.

Maybe a better solution would be to allow for protected functions, and add getters and setters for the variables?

**Comment by danh32** [comment]
The main issue is a lot of this stuff is meant to be implementation detail, not public api. So exposing it causes us to commit to these details, vs being flexible to changes in the future.

So I do think if you have a smaller set of these that you have a particular use-case in mind for, I'm open to considering. But I definitely don't want to make a blanket policy of everything being `protected`.

**Comment by RichyHBM** [comment]
OK, that's fair enough, maybe best to close this and I'll submit a PR if anything specific comes to mind

**Comment by danh32** [comment]
Sounds good to me! Sorry about the back and forth!

**Pull request closed without merging**
